name: build-server
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build
          git config --global user.name 'sebitommy123'
          git config --global user.email 'sebi.szafir@hotmail.com'
          git add dist/*
          git commit -am "Automated build"
          git push origin deploy