name: build-server
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          docker build . -t commonwealth
          export CR_PAT=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
          echo $CR_PAT | docker login ghcr.io -u sebitommy123 --password-stdin
          docker tag commonwealth ghcr.io/sebitommy123/commonwealth:latest
          docker push ghcr.io/sebitommy123/commonwealth:latest
